# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPXE_e-GgNl91VbxoUUZ178hjeVpeZe5
"""

import streamlit as st
import pdfplumber
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

st.set_page_config(page_title="AI Resume Screening System", layout="wide")

st.title("🤖 AI-Based Resume Screening System")
st.write("Upload resumes and paste job description to rank candidates intelligently.")

# Load model once
@st.cache_resource
def load_model():
    return SentenceTransformer('all-MiniLM-L6-v2')

model = load_model()

uploaded_files = st.file_uploader(
    "Upload Resume PDFs",
    type=["pdf"],
    accept_multiple_files=True
)

job_description = st.text_area("Paste Job Description Here", height=200)

if st.button("Screen Resumes"):

    if uploaded_files and job_description:

        resume_texts = []
        resume_names = []

        for file in uploaded_files:
            text = ""
            with pdfplumber.open(file) as pdf:
                for page in pdf.pages:
                    extracted = page.extract_text()
                    if extracted:
                        text += extracted + " "

            resume_texts.append(text)
            resume_names.append(file.name)

        # Embeddings
        resume_embeddings = model.encode(resume_texts)
        jd_embedding = model.encode([job_description])

        similarities = cosine_similarity(resume_embeddings, jd_embedding).flatten()

        # Skill matching
        jd_skills = ["python", "django", "rest", "postgresql", "docker", "aws", "git"]
        skill_overlap = []

        for text in resume_texts:
            text_lower = text.lower()
            matched = [skill for skill in jd_skills if skill in text_lower]
            overlap = len(matched) / len(jd_skills)
            skill_overlap.append(overlap)

        # Normalize similarity
        sim_norm = (similarities - similarities.min()) / (similarities.max() - similarities.min())
        final_scores = 0.7 * sim_norm + 0.3 * np.array(skill_overlap)

        results = pd.DataFrame({
            "Resume": resume_names,
            "Similarity Score": similarities,
            "Skill Overlap %": np.array(skill_overlap) * 100,
            "Final Score": final_scores
        }).sort_values(by="Final Score", ascending=False)

        st.success("Ranking Completed ✅")
        st.dataframe(results)

        # Download button
        csv = results.to_csv(index=False).encode('utf-8')
        st.download_button(
            "Download Results as CSV",
            csv,
            "ranked_candidates.csv",
            "text/csv"
        )

    else:
        st.warning("Please upload resumes and paste job description.")